# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prod - Continuous Integration / Continuous Deployment

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        dotnet: [5.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Cache node_modules folder
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cache-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - run: git fetch --no-tags --prune --depth=1 origin master

    - name: Install project dependencies
      run: yarn
      if: steps.yarn-cache.outputs.cache-hit != 'true'

    - run: yarn affected:build --parallel --base=origin/master
      env:
        CI: true

    - name: Build docker images
      run: yarn affected:docker --parallel --base=origin/master

    - name: Log in to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_AUTH_USER }}
        password: ${{ secrets.REGISTRY_AUTH_PASS }}

    - name: Deploy
      run: |
        yarn affected:deploy \
          --base=origin/master \
          --parallel \
          --args="--registry=osnoser1 --tag=${{ env.RELEASE_VERSION }}"
